import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import Review from 'App/Models/Review'

export default class extends BaseSeeder {
  public async run() {
    await Review.createMany([
      {
        productId: 1,
        name: 'Sarah Ahmed',
        email: 'sarah@example.com',
        description: 'Absolutely love the handwoven tapestry! The colors are even more vibrant in person. Great quality craftsmanship.',
        rating: '5',
        status: 'approved',
      },
      {
        productId: 2,
        name: 'Ali Hassan',
        email: 'ali@example.com',
        description: 'The ceramic dinner plates are beautiful and well-made. Very happy with my purchase!',
        rating: '5',
        status: 'approved',
      },
      {
        productId: 3,
        name: 'Fatima Khan',
        email: 'fatima@example.com',
        description: 'The coffee table is stunning! It arrived well-packaged and the quality exceeded my expectations.',
        rating: '5',
        status: 'approved',
      },
      {
        productId: 4,
        name: 'Ahmed Malik',
        email: 'ahmed@example.com',
        description: 'Beautiful cushion covers with excellent embroidery work. Adds a nice touch to my living room.',
        rating: '4',
        status: 'approved',
      },
      {
        productId: 5,
        name: 'Zainab Ali',
        email: 'zainab@example.com',
        description: 'The macrame plant hanger is exactly what I was looking for. Perfect for my indoor plants!',
        rating: '5',
        status: 'approved',
      },
      {
        productId: 6,
        name: 'Hassan Raza',
        email: 'hassan@example.com',
        description: 'The decorative mirror looks amazing on my wall. Great craftsmanship and fast delivery.',
        rating: '5',
        status: 'approved',
      },
      {
        productId: 7,
        name: 'Aisha Siddiqui',
        email: 'aisha@example.com',
        description: 'Love the pottery set! Each piece is unique and beautifully made. Highly recommend!',
        rating: '5',
        status: 'approved',
      },
      {
        productId: 8,
        name: 'Bilal Ahmed',
        email: 'bilal@example.com',
        description: 'The storage baskets are perfect for organizing. Good quality and look great!',
        rating: '4',
        status: 'approved',
      },
      {
        productId: 9,
        name: 'Mariam Noor',
        email: 'mariam@example.com',
        description: 'The silk curtains are absolutely gorgeous! The embroidery is exquisite.',
        rating: '5',
        status: 'approved',
      },
      {
        productId: 10,
        name: 'Usman Tariq',
        email: 'usman@example.com',
        description: 'Very satisfied with the bookshelf. Sturdy and well-crafted. Worth the price!',
        rating: '5',
        status: 'approved',
      },
      {
        productId: 11,
        name: 'Hina Malik',
        email: 'hina@example.com',
        description: 'The terracotta planters are so colorful and unique. Love supporting local artisans!',
        rating: '5',
        status: 'approved',
      },
      {
        productId: 12,
        name: 'Imran Shah',
        email: 'imran@example.com',
        description: 'Beautiful brass candle holders. Creates a wonderful ambiance in my home.',
        rating: '4',
        status: 'approved',
      },
      {
        productId: 1,
        name: 'Sana Rizvi',
        email: 'sana@example.com',
        description: 'Amazing quality products! Will definitely order again. Highly recommend Udari Crafts!',
        rating: '5',
        status: 'approved',
      },
      {
        productId: 2,
        name: 'Kamran Javed',
        email: 'kamran@example.com',
        description: 'Great experience shopping here. Products are authentic and prices are reasonable.',
        rating: '5',
        status: 'approved',
      },
      {
        productId: 3,
        name: 'Ayesha Farooq',
        email: 'ayesha@example.com',
        description: 'The handcrafted items are truly special. You can tell they are made with care and skill.',
        rating: '5',
        status: 'approved',
      },
    ])
  }
}
